language: python
python:
  - "2.6"
  - "2.7"
env:
  - ANSIBLE_VERSION: 1.9.4
  - ANSIBLE_VERSION: 2.0.0.2

install:
  - pip install -q ansible==$ANSIBLE_VERSION
  - pip install -r test-deps.txt
  - python setup.py -q install

script: tox
